title: Geo1088

permalink: /posts/:title

defaults:
    -
        scope:
            path: ""
        values:
            layout: default

# Build settings
markdown: kramdown
exclude:
    - Gemfile
    - Gemfile.lock

url: 'https://geo1088-github-io-geo1088.c9users.io'